### ISSUE TITLE
Unable to compile the project

### ISSUE THREAD

**Issue by auxilim** [israelglory/Job-UI#1]
Hi, 

I just tried to compile your project, and I have a working flutter tools, but I could not comoile the project. Here is the ouput:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.window:window-java:1.0.0-beta04.
        AAR metadata file: C:\Users\mouge\.gradle\caches\transforms-2\files-2.1\625039eaad011f884ddd84f857a44b7f\jetified-window-java-1.0.0-beta04\META-INF\com\android\build\gradle\aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.window:window:1.0.0-beta04.
        AAR metadata file: C:\Users\mouge\.gradle\caches\transforms-2\files-2.1\a78fdf90e4c1f8464b19895cfb365f3f\jetified-window-1.0.0-beta04\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

Any idea why?

**Comment by israelglory** [comment]
Your version of the build tool?
My compileSdkVersion is 30
I'll advise you to change it to 30 instead of 31
You can check your version of the build tool too if it corresponds to the minCompileSDK and compileSdkVerion...
Because I can compile it here and I've been able to output the .apk file 
link to the apk: https://mega.nz/file/BlEWkR6Y#JaEdvv7HXDxhIRbwS6xakp5VzSfTU3qQarYBiov3u5s

**Comment by auxilim** [comment]
Yes, it worked when I switched my version of compileSdkVersion 

Thank you
